// Admin defines the admin API service for the game management UI.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v1/admin.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StageScoreVerifiedFilter int32

const (
	StageScoreVerifiedFilter_STAGE_SCORE_VERIFIED_FILTER_UNSPECIFIED     StageScoreVerifiedFilter = 0
	StageScoreVerifiedFilter_STAGE_SCORE_VERIFIED_FILTER_ALL             StageScoreVerifiedFilter = 1
	StageScoreVerifiedFilter_STAGE_SCORE_VERIFIED_FILTER_ONLY_UNVERIFIED StageScoreVerifiedFilter = 2
)

// Enum value maps for StageScoreVerifiedFilter.
var (
	StageScoreVerifiedFilter_name = map[int32]string{
		0: "STAGE_SCORE_VERIFIED_FILTER_UNSPECIFIED",
		1: "STAGE_SCORE_VERIFIED_FILTER_ALL",
		2: "STAGE_SCORE_VERIFIED_FILTER_ONLY_UNVERIFIED",
	}
	StageScoreVerifiedFilter_value = map[string]int32{
		"STAGE_SCORE_VERIFIED_FILTER_UNSPECIFIED":     0,
		"STAGE_SCORE_VERIFIED_FILTER_ALL":             1,
		"STAGE_SCORE_VERIFIED_FILTER_ONLY_UNVERIFIED": 2,
	}
)

func (x StageScoreVerifiedFilter) Enum() *StageScoreVerifiedFilter {
	p := new(StageScoreVerifiedFilter)
	*p = x
	return p
}

func (x StageScoreVerifiedFilter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageScoreVerifiedFilter) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_admin_proto_enumTypes[0].Descriptor()
}

func (StageScoreVerifiedFilter) Type() protoreflect.EnumType {
	return &file_api_v1_admin_proto_enumTypes[0]
}

func (x StageScoreVerifiedFilter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StageScoreVerifiedFilter.Descriptor instead.
func (StageScoreVerifiedFilter) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{0}
}

type AdminServiceCreatePlayerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in api/v1/admin.proto.
	EventKey      string             `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	PlayerData    *PlayerData        `protobuf:"bytes,2,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
	PhoneNumber   string             `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Registration  *EventRegistration `protobuf:"bytes,4,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminServiceCreatePlayerRequest) Reset() {
	*x = AdminServiceCreatePlayerRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminServiceCreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminServiceCreatePlayerRequest) ProtoMessage() {}

func (x *AdminServiceCreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminServiceCreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*AdminServiceCreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in api/v1/admin.proto.
func (x *AdminServiceCreatePlayerRequest) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

func (x *AdminServiceCreatePlayerRequest) GetPlayerData() *PlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

func (x *AdminServiceCreatePlayerRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *AdminServiceCreatePlayerRequest) GetRegistration() *EventRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type AdminServiceCreatePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminServiceCreatePlayerResponse) Reset() {
	*x = AdminServiceCreatePlayerResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminServiceCreatePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminServiceCreatePlayerResponse) ProtoMessage() {}

func (x *AdminServiceCreatePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminServiceCreatePlayerResponse.ProtoReflect.Descriptor instead.
func (*AdminServiceCreatePlayerResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminServiceCreatePlayerResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type UpdatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerData    *PlayerData            `protobuf:"bytes,2,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
	Registration  *EventRegistration     `protobuf:"bytes,3,opt,name=registration,proto3" json:"registration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerRequest) Reset() {
	*x = UpdatePlayerRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerRequest) ProtoMessage() {}

func (x *UpdatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *UpdatePlayerRequest) GetPlayerData() *PlayerData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

func (x *UpdatePlayerRequest) GetRegistration() *EventRegistration {
	if x != nil {
		return x.Registration
	}
	return nil
}

type UpdatePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlayerResponse) Reset() {
	*x = UpdatePlayerResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerResponse) ProtoMessage() {}

func (x *UpdatePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerResponse.ProtoReflect.Descriptor instead.
func (*UpdatePlayerResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePlayerResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type ListPlayersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventKey      string                 `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersRequest) Reset() {
	*x = ListPlayersRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersRequest) ProtoMessage() {}

func (x *ListPlayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersRequest.ProtoReflect.Descriptor instead.
func (*ListPlayersRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlayersRequest) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

type ListPlayersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlayersResponse) Reset() {
	*x = ListPlayersResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlayersResponse) ProtoMessage() {}

func (x *ListPlayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlayersResponse.ProtoReflect.Descriptor instead.
func (*ListPlayersResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListPlayersResponse) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Rule struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VenueDescription string                 `protobuf:"bytes,2,opt,name=venue_description,json=venueDescription,proto3" json:"venue_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_api_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetVenueDescription() string {
	if x != nil {
		return x.VenueDescription
	}
	return ""
}

type Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Venue         *Venue                 `protobuf:"bytes,2,opt,name=venue,proto3" json:"venue,omitempty"`
	Rule          *Rule                  `protobuf:"bytes,3,opt,name=rule,proto3" json:"rule,omitempty"`
	Rank          int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	DurationMin   int32                  `protobuf:"varint,5,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_api_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *Stage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stage) GetVenue() *Venue {
	if x != nil {
		return x.Venue
	}
	return nil
}

func (x *Stage) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *Stage) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Stage) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

type ListVenuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVenuesRequest) Reset() {
	*x = ListVenuesRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVenuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVenuesRequest) ProtoMessage() {}

func (x *ListVenuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVenuesRequest.ProtoReflect.Descriptor instead.
func (*ListVenuesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{8}
}

type ListVenuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Venues        []*Venue               `protobuf:"bytes,1,rep,name=venues,proto3" json:"venues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVenuesResponse) Reset() {
	*x = ListVenuesResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVenuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVenuesResponse) ProtoMessage() {}

func (x *ListVenuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVenuesResponse.ProtoReflect.Descriptor instead.
func (*ListVenuesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListVenuesResponse) GetVenues() []*Venue {
	if x != nil {
		return x.Venues
	}
	return nil
}

type UpdateStageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StageId          string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	VenueId          string                 `protobuf:"bytes,2,opt,name=venue_id,json=venueId,proto3" json:"venue_id,omitempty"`
	VenueDescription string                 `protobuf:"bytes,3,opt,name=venue_description,json=venueDescription,proto3" json:"venue_description,omitempty"`
	Rank             int32                  `protobuf:"varint,4,opt,name=rank,proto3" json:"rank,omitempty"`
	DurationMin      int32                  `protobuf:"varint,5,opt,name=duration_min,json=durationMin,proto3" json:"duration_min,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateStageRequest) Reset() {
	*x = UpdateStageRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStageRequest) ProtoMessage() {}

func (x *UpdateStageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStageRequest.ProtoReflect.Descriptor instead.
func (*UpdateStageRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStageRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *UpdateStageRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *UpdateStageRequest) GetVenueDescription() string {
	if x != nil {
		return x.VenueDescription
	}
	return ""
}

func (x *UpdateStageRequest) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *UpdateStageRequest) GetDurationMin() int32 {
	if x != nil {
		return x.DurationMin
	}
	return 0
}

type UpdateStageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStageResponse) Reset() {
	*x = UpdateStageResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStageResponse) ProtoMessage() {}

func (x *UpdateStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStageResponse.ProtoReflect.Descriptor instead.
func (*UpdateStageResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{11}
}

type ListEventStagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventKey      string                 `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventStagesRequest) Reset() {
	*x = ListEventStagesRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventStagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventStagesRequest) ProtoMessage() {}

func (x *ListEventStagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventStagesRequest.ProtoReflect.Descriptor instead.
func (*ListEventStagesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListEventStagesRequest) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

type ListEventStagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stages        []*Stage               `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventStagesResponse) Reset() {
	*x = ListEventStagesResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventStagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventStagesResponse) ProtoMessage() {}

func (x *ListEventStagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventStagesResponse.ProtoReflect.Descriptor instead.
func (*ListEventStagesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ListEventStagesResponse) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

type AdjustmentTemplateData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adjustment    *AdjustmentData        `protobuf:"bytes,1,opt,name=adjustment,proto3" json:"adjustment,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	EventKey      string                 `protobuf:"bytes,3,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	StageId       *string                `protobuf:"bytes,4,opt,name=stage_id,json=stageId,proto3,oneof" json:"stage_id,omitempty"`
	IsVisible     bool                   `protobuf:"varint,5,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustmentTemplateData) Reset() {
	*x = AdjustmentTemplateData{}
	mi := &file_api_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustmentTemplateData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustmentTemplateData) ProtoMessage() {}

func (x *AdjustmentTemplateData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustmentTemplateData.ProtoReflect.Descriptor instead.
func (*AdjustmentTemplateData) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *AdjustmentTemplateData) GetAdjustment() *AdjustmentData {
	if x != nil {
		return x.Adjustment
	}
	return nil
}

func (x *AdjustmentTemplateData) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *AdjustmentTemplateData) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

func (x *AdjustmentTemplateData) GetStageId() string {
	if x != nil && x.StageId != nil {
		return *x.StageId
	}
	return ""
}

func (x *AdjustmentTemplateData) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

type AdjustmentTemplate struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *AdjustmentTemplateData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustmentTemplate) Reset() {
	*x = AdjustmentTemplate{}
	mi := &file_api_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustmentTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustmentTemplate) ProtoMessage() {}

func (x *AdjustmentTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustmentTemplate.ProtoReflect.Descriptor instead.
func (*AdjustmentTemplate) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AdjustmentTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdjustmentTemplate) GetData() *AdjustmentTemplateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateAdjustmentTemplateRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *AdjustmentTemplateData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdjustmentTemplateRequest) Reset() {
	*x = CreateAdjustmentTemplateRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdjustmentTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdjustmentTemplateRequest) ProtoMessage() {}

func (x *CreateAdjustmentTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdjustmentTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateAdjustmentTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *CreateAdjustmentTemplateRequest) GetData() *AdjustmentTemplateData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateAdjustmentTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdjustmentTemplateResponse) Reset() {
	*x = CreateAdjustmentTemplateResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdjustmentTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdjustmentTemplateResponse) ProtoMessage() {}

func (x *CreateAdjustmentTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdjustmentTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateAdjustmentTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{17}
}

type UpdateAdjustmentTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *AdjustmentTemplate    `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdjustmentTemplateRequest) Reset() {
	*x = UpdateAdjustmentTemplateRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdjustmentTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdjustmentTemplateRequest) ProtoMessage() {}

func (x *UpdateAdjustmentTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdjustmentTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdjustmentTemplateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateAdjustmentTemplateRequest) GetTemplate() *AdjustmentTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type UpdateAdjustmentTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAdjustmentTemplateResponse) Reset() {
	*x = UpdateAdjustmentTemplateResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAdjustmentTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdjustmentTemplateResponse) ProtoMessage() {}

func (x *UpdateAdjustmentTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdjustmentTemplateResponse.ProtoReflect.Descriptor instead.
func (*UpdateAdjustmentTemplateResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{19}
}

type ListAdjustmentTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventKey      string                 `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdjustmentTemplatesRequest) Reset() {
	*x = ListAdjustmentTemplatesRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdjustmentTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdjustmentTemplatesRequest) ProtoMessage() {}

func (x *ListAdjustmentTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdjustmentTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListAdjustmentTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListAdjustmentTemplatesRequest) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

type ListAdjustmentTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*AdjustmentTemplate  `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdjustmentTemplatesResponse) Reset() {
	*x = ListAdjustmentTemplatesResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdjustmentTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdjustmentTemplatesResponse) ProtoMessage() {}

func (x *ListAdjustmentTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdjustmentTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListAdjustmentTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *ListAdjustmentTemplatesResponse) GetTemplates() []*AdjustmentTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type Score struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *ScoreData             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Score) Reset() {
	*x = Score{}
	mi := &file_api_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Score) ProtoMessage() {}

func (x *Score) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Score.ProtoReflect.Descriptor instead.
func (*Score) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *Score) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Score) GetData() *ScoreData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ScoreData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         uint32                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreData) Reset() {
	*x = ScoreData{}
	mi := &file_api_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreData) ProtoMessage() {}

func (x *ScoreData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreData.ProtoReflect.Descriptor instead.
func (*ScoreData) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{23}
}

func (x *ScoreData) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Adjustment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *AdjustmentData        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Adjustment) Reset() {
	*x = Adjustment{}
	mi := &file_api_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Adjustment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adjustment) ProtoMessage() {}

func (x *Adjustment) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adjustment.ProtoReflect.Descriptor instead.
func (*Adjustment) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *Adjustment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Adjustment) GetData() *AdjustmentData {
	if x != nil {
		return x.Data
	}
	return nil
}

type AdjustmentData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustmentData) Reset() {
	*x = AdjustmentData{}
	mi := &file_api_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustmentData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustmentData) ProtoMessage() {}

func (x *AdjustmentData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustmentData.ProtoReflect.Descriptor instead.
func (*AdjustmentData) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *AdjustmentData) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AdjustmentData) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type StageScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Score         *Score                 `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
	Adjustments   []*Adjustment          `protobuf:"bytes,4,rep,name=adjustments,proto3" json:"adjustments,omitempty"`
	IsVerified    bool                   `protobuf:"varint,5,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageScore) Reset() {
	*x = StageScore{}
	mi := &file_api_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageScore) ProtoMessage() {}

func (x *StageScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageScore.ProtoReflect.Descriptor instead.
func (*StageScore) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *StageScore) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageScore) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StageScore) GetScore() *Score {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *StageScore) GetAdjustments() []*Adjustment {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

func (x *StageScore) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type StageScoreData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Score         *ScoreData             `protobuf:"bytes,3,opt,name=score,proto3" json:"score,omitempty"`
	Adjustments   []*AdjustmentData      `protobuf:"bytes,4,rep,name=adjustments,proto3" json:"adjustments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StageScoreData) Reset() {
	*x = StageScoreData{}
	mi := &file_api_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StageScoreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StageScoreData) ProtoMessage() {}

func (x *StageScoreData) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StageScoreData.ProtoReflect.Descriptor instead.
func (*StageScoreData) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *StageScoreData) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *StageScoreData) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StageScoreData) GetScore() *ScoreData {
	if x != nil {
		return x.Score
	}
	return nil
}

func (x *StageScoreData) GetAdjustments() []*AdjustmentData {
	if x != nil {
		return x.Adjustments
	}
	return nil
}

type CreateStageScoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Data           *StageScoreData        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	IdempotencyKey *string                `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateStageScoreRequest) Reset() {
	*x = CreateStageScoreRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStageScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStageScoreRequest) ProtoMessage() {}

func (x *CreateStageScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStageScoreRequest.ProtoReflect.Descriptor instead.
func (*CreateStageScoreRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *CreateStageScoreRequest) GetData() *StageScoreData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CreateStageScoreRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

type CreateStageScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *StageScore            `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStageScoreResponse) Reset() {
	*x = CreateStageScoreResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStageScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStageScoreResponse) ProtoMessage() {}

func (x *CreateStageScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStageScoreResponse.ProtoReflect.Descriptor instead.
func (*CreateStageScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *CreateStageScoreResponse) GetScore() *StageScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type UpdateStageScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *StageScore            `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStageScoreRequest) Reset() {
	*x = UpdateStageScoreRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStageScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStageScoreRequest) ProtoMessage() {}

func (x *UpdateStageScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStageScoreRequest.ProtoReflect.Descriptor instead.
func (*UpdateStageScoreRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateStageScoreRequest) GetScore() *StageScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type UpdateStageScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Score         *StageScore            `protobuf:"bytes,1,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStageScoreResponse) Reset() {
	*x = UpdateStageScoreResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStageScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStageScoreResponse) ProtoMessage() {}

func (x *UpdateStageScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStageScoreResponse.ProtoReflect.Descriptor instead.
func (*UpdateStageScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateStageScoreResponse) GetScore() *StageScore {
	if x != nil {
		return x.Score
	}
	return nil
}

type ListStageScoresRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	EventKey string                 `protobuf:"bytes,1,opt,name=event_key,json=eventKey,proto3" json:"event_key,omitempty"`
	// Default is STAGE_SCORE_VERIFIED_FILTER_ALL.
	VerifiedFilter *StageScoreVerifiedFilter `protobuf:"varint,2,opt,name=verified_filter,json=verifiedFilter,proto3,enum=api.v1.StageScoreVerifiedFilter,oneof" json:"verified_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListStageScoresRequest) Reset() {
	*x = ListStageScoresRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStageScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStageScoresRequest) ProtoMessage() {}

func (x *ListStageScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStageScoresRequest.ProtoReflect.Descriptor instead.
func (*ListStageScoresRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{32}
}

func (x *ListStageScoresRequest) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

func (x *ListStageScoresRequest) GetVerifiedFilter() StageScoreVerifiedFilter {
	if x != nil && x.VerifiedFilter != nil {
		return *x.VerifiedFilter
	}
	return StageScoreVerifiedFilter_STAGE_SCORE_VERIFIED_FILTER_UNSPECIFIED
}

type ListStageScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*StageScore          `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStageScoresResponse) Reset() {
	*x = ListStageScoresResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStageScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStageScoresResponse) ProtoMessage() {}

func (x *ListStageScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStageScoresResponse.ProtoReflect.Descriptor instead.
func (*ListStageScoresResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{33}
}

func (x *ListStageScoresResponse) GetScores() []*StageScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

type DeleteStageScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StageId       string                 `protobuf:"bytes,1,opt,name=stage_id,json=stageId,proto3" json:"stage_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStageScoreRequest) Reset() {
	*x = DeleteStageScoreRequest{}
	mi := &file_api_v1_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStageScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStageScoreRequest) ProtoMessage() {}

func (x *DeleteStageScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStageScoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteStageScoreRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteStageScoreRequest) GetStageId() string {
	if x != nil {
		return x.StageId
	}
	return ""
}

func (x *DeleteStageScoreRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type DeleteStageScoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStageScoreResponse) Reset() {
	*x = DeleteStageScoreResponse{}
	mi := &file_api_v1_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStageScoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStageScoreResponse) ProtoMessage() {}

func (x *DeleteStageScoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStageScoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteStageScoreResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_admin_proto_rawDescGZIP(), []int{35}
}

var File_api_v1_admin_proto protoreflect.FileDescriptor

const file_api_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/admin.proto\x12\x06api.v1\x1a\x13api/v1/shared.proto\"\xd9\x01\n" +
	"\x1fAdminServiceCreatePlayerRequest\x12\x1f\n" +
	"\tevent_key\x18\x01 \x01(\tB\x02\x18\x01R\beventKey\x123\n" +
	"\vplayer_data\x18\x02 \x01(\v2\x12.api.v1.PlayerDataR\n" +
	"playerData\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12=\n" +
	"\fregistration\x18\x04 \x01(\v2\x19.api.v1.EventRegistrationR\fregistration\"J\n" +
	" AdminServiceCreatePlayerResponse\x12&\n" +
	"\x06player\x18\x01 \x01(\v2\x0e.api.v1.PlayerR\x06player\"\xa6\x01\n" +
	"\x13UpdatePlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x123\n" +
	"\vplayer_data\x18\x02 \x01(\v2\x12.api.v1.PlayerDataR\n" +
	"playerData\x12=\n" +
	"\fregistration\x18\x03 \x01(\v2\x19.api.v1.EventRegistrationR\fregistration\">\n" +
	"\x14UpdatePlayerResponse\x12&\n" +
	"\x06player\x18\x01 \x01(\v2\x0e.api.v1.PlayerR\x06player\"1\n" +
	"\x12ListPlayersRequest\x12\x1b\n" +
	"\tevent_key\x18\x01 \x01(\tR\beventKey\"?\n" +
	"\x13ListPlayersResponse\x12(\n" +
	"\aplayers\x18\x01 \x03(\v2\x0e.api.v1.PlayerR\aplayers\"C\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11venue_description\x18\x02 \x01(\tR\x10venueDescription\"\x95\x01\n" +
	"\x05Stage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x05venue\x18\x02 \x01(\v2\r.api.v1.VenueR\x05venue\x12 \n" +
	"\x04rule\x18\x03 \x01(\v2\f.api.v1.RuleR\x04rule\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12!\n" +
	"\fduration_min\x18\x05 \x01(\x05R\vdurationMin\"\x13\n" +
	"\x11ListVenuesRequest\";\n" +
	"\x12ListVenuesResponse\x12%\n" +
	"\x06venues\x18\x01 \x03(\v2\r.api.v1.VenueR\x06venues\"\xae\x01\n" +
	"\x12UpdateStageRequest\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x19\n" +
	"\bvenue_id\x18\x02 \x01(\tR\avenueId\x12+\n" +
	"\x11venue_description\x18\x03 \x01(\tR\x10venueDescription\x12\x12\n" +
	"\x04rank\x18\x04 \x01(\x05R\x04rank\x12!\n" +
	"\fduration_min\x18\x05 \x01(\x05R\vdurationMin\"\x15\n" +
	"\x13UpdateStageResponse\"5\n" +
	"\x16ListEventStagesRequest\x12\x1b\n" +
	"\tevent_key\x18\x01 \x01(\tR\beventKey\"@\n" +
	"\x17ListEventStagesResponse\x12%\n" +
	"\x06stages\x18\x01 \x03(\v2\r.api.v1.StageR\x06stages\"\xcd\x01\n" +
	"\x16AdjustmentTemplateData\x126\n" +
	"\n" +
	"adjustment\x18\x01 \x01(\v2\x16.api.v1.AdjustmentDataR\n" +
	"adjustment\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x1b\n" +
	"\tevent_key\x18\x03 \x01(\tR\beventKey\x12\x1e\n" +
	"\bstage_id\x18\x04 \x01(\tH\x00R\astageId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_visible\x18\x05 \x01(\bR\tisVisibleB\v\n" +
	"\t_stage_id\"X\n" +
	"\x12AdjustmentTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.api.v1.AdjustmentTemplateDataR\x04data\"U\n" +
	"\x1fCreateAdjustmentTemplateRequest\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.api.v1.AdjustmentTemplateDataR\x04data\"\"\n" +
	" CreateAdjustmentTemplateResponse\"Y\n" +
	"\x1fUpdateAdjustmentTemplateRequest\x126\n" +
	"\btemplate\x18\x01 \x01(\v2\x1a.api.v1.AdjustmentTemplateR\btemplate\"\"\n" +
	" UpdateAdjustmentTemplateResponse\"=\n" +
	"\x1eListAdjustmentTemplatesRequest\x12\x1b\n" +
	"\tevent_key\x18\x01 \x01(\tR\beventKey\"[\n" +
	"\x1fListAdjustmentTemplatesResponse\x128\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1a.api.v1.AdjustmentTemplateR\ttemplates\">\n" +
	"\x05Score\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x04data\x18\x02 \x01(\v2\x11.api.v1.ScoreDataR\x04data\"!\n" +
	"\tScoreData\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\"H\n" +
	"\n" +
	"Adjustment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.api.v1.AdjustmentDataR\x04data\"<\n" +
	"\x0eAdjustmentData\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xc0\x01\n" +
	"\n" +
	"StageScore\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12#\n" +
	"\x05score\x18\x03 \x01(\v2\r.api.v1.ScoreR\x05score\x124\n" +
	"\vadjustments\x18\x04 \x03(\v2\x12.api.v1.AdjustmentR\vadjustments\x12\x1f\n" +
	"\vis_verified\x18\x05 \x01(\bR\n" +
	"isVerified\"\xab\x01\n" +
	"\x0eStageScoreData\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12'\n" +
	"\x05score\x18\x03 \x01(\v2\x11.api.v1.ScoreDataR\x05score\x128\n" +
	"\vadjustments\x18\x04 \x03(\v2\x16.api.v1.AdjustmentDataR\vadjustments\"\x87\x01\n" +
	"\x17CreateStageScoreRequest\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.api.v1.StageScoreDataR\x04data\x12,\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tH\x00R\x0eidempotencyKey\x88\x01\x01B\x12\n" +
	"\x10_idempotency_key\"D\n" +
	"\x18CreateStageScoreResponse\x12(\n" +
	"\x05score\x18\x01 \x01(\v2\x12.api.v1.StageScoreR\x05score\"C\n" +
	"\x17UpdateStageScoreRequest\x12(\n" +
	"\x05score\x18\x01 \x01(\v2\x12.api.v1.StageScoreR\x05score\"D\n" +
	"\x18UpdateStageScoreResponse\x12(\n" +
	"\x05score\x18\x01 \x01(\v2\x12.api.v1.StageScoreR\x05score\"\x99\x01\n" +
	"\x16ListStageScoresRequest\x12\x1b\n" +
	"\tevent_key\x18\x01 \x01(\tR\beventKey\x12N\n" +
	"\x0fverified_filter\x18\x02 \x01(\x0e2 .api.v1.StageScoreVerifiedFilterH\x00R\x0everifiedFilter\x88\x01\x01B\x12\n" +
	"\x10_verified_filter\"E\n" +
	"\x17ListStageScoresResponse\x12*\n" +
	"\x06scores\x18\x01 \x03(\v2\x12.api.v1.StageScoreR\x06scores\"Q\n" +
	"\x17DeleteStageScoreRequest\x12\x19\n" +
	"\bstage_id\x18\x01 \x01(\tR\astageId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\x1a\n" +
	"\x18DeleteStageScoreResponse*\x9d\x01\n" +
	"\x18StageScoreVerifiedFilter\x12+\n" +
	"'STAGE_SCORE_VERIFIED_FILTER_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSTAGE_SCORE_VERIFIED_FILTER_ALL\x10\x01\x12/\n" +
	"+STAGE_SCORE_VERIFIED_FILTER_ONLY_UNVERIFIED\x10\x022\xa2\t\n" +
	"\fAdminService\x12c\n" +
	"\fCreatePlayer\x12'.api.v1.AdminServiceCreatePlayerRequest\x1a(.api.v1.AdminServiceCreatePlayerResponse\"\x00\x12K\n" +
	"\fUpdatePlayer\x12\x1b.api.v1.UpdatePlayerRequest\x1a\x1c.api.v1.UpdatePlayerResponse\"\x00\x12H\n" +
	"\vListPlayers\x12\x1a.api.v1.ListPlayersRequest\x1a\x1b.api.v1.ListPlayersResponse\"\x00\x12E\n" +
	"\n" +
	"ListVenues\x12\x19.api.v1.ListVenuesRequest\x1a\x1a.api.v1.ListVenuesResponse\"\x00\x12H\n" +
	"\vUpdateStage\x12\x1a.api.v1.UpdateStageRequest\x1a\x1b.api.v1.UpdateStageResponse\"\x00\x12T\n" +
	"\x0fListEventStages\x12\x1e.api.v1.ListEventStagesRequest\x1a\x1f.api.v1.ListEventStagesResponse\"\x00\x12o\n" +
	"\x18CreateAdjustmentTemplate\x12'.api.v1.CreateAdjustmentTemplateRequest\x1a(.api.v1.CreateAdjustmentTemplateResponse\"\x00\x12o\n" +
	"\x18UpdateAdjustmentTemplate\x12'.api.v1.UpdateAdjustmentTemplateRequest\x1a(.api.v1.UpdateAdjustmentTemplateResponse\"\x00\x12l\n" +
	"\x17ListAdjustmentTemplates\x12&.api.v1.ListAdjustmentTemplatesRequest\x1a'.api.v1.ListAdjustmentTemplatesResponse\"\x00\x12W\n" +
	"\x10CreateStageScore\x12\x1f.api.v1.CreateStageScoreRequest\x1a .api.v1.CreateStageScoreResponse\"\x00\x12W\n" +
	"\x10UpdateStageScore\x12\x1f.api.v1.UpdateStageScoreRequest\x1a .api.v1.UpdateStageScoreResponse\"\x00\x12T\n" +
	"\x0fListStageScores\x12\x1e.api.v1.ListStageScoresRequest\x1a\x1f.api.v1.ListStageScoresResponse\"\x00\x12W\n" +
	"\x10DeleteStageScore\x12\x1f.api.v1.DeleteStageScoreRequest\x1a .api.v1.DeleteStageScoreResponse\"\x00B@Z>github.com/pubgolf/pubgolf/api/internal/lib/proto/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_admin_proto_rawDescOnce sync.Once
	file_api_v1_admin_proto_rawDescData []byte
)

func file_api_v1_admin_proto_rawDescGZIP() []byte {
	file_api_v1_admin_proto_rawDescOnce.Do(func() {
		file_api_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_admin_proto_rawDesc), len(file_api_v1_admin_proto_rawDesc)))
	})
	return file_api_v1_admin_proto_rawDescData
}

var file_api_v1_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_api_v1_admin_proto_goTypes = []any{
	(StageScoreVerifiedFilter)(0),            // 0: api.v1.StageScoreVerifiedFilter
	(*AdminServiceCreatePlayerRequest)(nil),  // 1: api.v1.AdminServiceCreatePlayerRequest
	(*AdminServiceCreatePlayerResponse)(nil), // 2: api.v1.AdminServiceCreatePlayerResponse
	(*UpdatePlayerRequest)(nil),              // 3: api.v1.UpdatePlayerRequest
	(*UpdatePlayerResponse)(nil),             // 4: api.v1.UpdatePlayerResponse
	(*ListPlayersRequest)(nil),               // 5: api.v1.ListPlayersRequest
	(*ListPlayersResponse)(nil),              // 6: api.v1.ListPlayersResponse
	(*Rule)(nil),                             // 7: api.v1.Rule
	(*Stage)(nil),                            // 8: api.v1.Stage
	(*ListVenuesRequest)(nil),                // 9: api.v1.ListVenuesRequest
	(*ListVenuesResponse)(nil),               // 10: api.v1.ListVenuesResponse
	(*UpdateStageRequest)(nil),               // 11: api.v1.UpdateStageRequest
	(*UpdateStageResponse)(nil),              // 12: api.v1.UpdateStageResponse
	(*ListEventStagesRequest)(nil),           // 13: api.v1.ListEventStagesRequest
	(*ListEventStagesResponse)(nil),          // 14: api.v1.ListEventStagesResponse
	(*AdjustmentTemplateData)(nil),           // 15: api.v1.AdjustmentTemplateData
	(*AdjustmentTemplate)(nil),               // 16: api.v1.AdjustmentTemplate
	(*CreateAdjustmentTemplateRequest)(nil),  // 17: api.v1.CreateAdjustmentTemplateRequest
	(*CreateAdjustmentTemplateResponse)(nil), // 18: api.v1.CreateAdjustmentTemplateResponse
	(*UpdateAdjustmentTemplateRequest)(nil),  // 19: api.v1.UpdateAdjustmentTemplateRequest
	(*UpdateAdjustmentTemplateResponse)(nil), // 20: api.v1.UpdateAdjustmentTemplateResponse
	(*ListAdjustmentTemplatesRequest)(nil),   // 21: api.v1.ListAdjustmentTemplatesRequest
	(*ListAdjustmentTemplatesResponse)(nil),  // 22: api.v1.ListAdjustmentTemplatesResponse
	(*Score)(nil),                            // 23: api.v1.Score
	(*ScoreData)(nil),                        // 24: api.v1.ScoreData
	(*Adjustment)(nil),                       // 25: api.v1.Adjustment
	(*AdjustmentData)(nil),                   // 26: api.v1.AdjustmentData
	(*StageScore)(nil),                       // 27: api.v1.StageScore
	(*StageScoreData)(nil),                   // 28: api.v1.StageScoreData
	(*CreateStageScoreRequest)(nil),          // 29: api.v1.CreateStageScoreRequest
	(*CreateStageScoreResponse)(nil),         // 30: api.v1.CreateStageScoreResponse
	(*UpdateStageScoreRequest)(nil),          // 31: api.v1.UpdateStageScoreRequest
	(*UpdateStageScoreResponse)(nil),         // 32: api.v1.UpdateStageScoreResponse
	(*ListStageScoresRequest)(nil),           // 33: api.v1.ListStageScoresRequest
	(*ListStageScoresResponse)(nil),          // 34: api.v1.ListStageScoresResponse
	(*DeleteStageScoreRequest)(nil),          // 35: api.v1.DeleteStageScoreRequest
	(*DeleteStageScoreResponse)(nil),         // 36: api.v1.DeleteStageScoreResponse
	(*PlayerData)(nil),                       // 37: api.v1.PlayerData
	(*EventRegistration)(nil),                // 38: api.v1.EventRegistration
	(*Player)(nil),                           // 39: api.v1.Player
	(*Venue)(nil),                            // 40: api.v1.Venue
}
var file_api_v1_admin_proto_depIdxs = []int32{
	37, // 0: api.v1.AdminServiceCreatePlayerRequest.player_data:type_name -> api.v1.PlayerData
	38, // 1: api.v1.AdminServiceCreatePlayerRequest.registration:type_name -> api.v1.EventRegistration
	39, // 2: api.v1.AdminServiceCreatePlayerResponse.player:type_name -> api.v1.Player
	37, // 3: api.v1.UpdatePlayerRequest.player_data:type_name -> api.v1.PlayerData
	38, // 4: api.v1.UpdatePlayerRequest.registration:type_name -> api.v1.EventRegistration
	39, // 5: api.v1.UpdatePlayerResponse.player:type_name -> api.v1.Player
	39, // 6: api.v1.ListPlayersResponse.players:type_name -> api.v1.Player
	40, // 7: api.v1.Stage.venue:type_name -> api.v1.Venue
	7,  // 8: api.v1.Stage.rule:type_name -> api.v1.Rule
	40, // 9: api.v1.ListVenuesResponse.venues:type_name -> api.v1.Venue
	8,  // 10: api.v1.ListEventStagesResponse.stages:type_name -> api.v1.Stage
	26, // 11: api.v1.AdjustmentTemplateData.adjustment:type_name -> api.v1.AdjustmentData
	15, // 12: api.v1.AdjustmentTemplate.data:type_name -> api.v1.AdjustmentTemplateData
	15, // 13: api.v1.CreateAdjustmentTemplateRequest.data:type_name -> api.v1.AdjustmentTemplateData
	16, // 14: api.v1.UpdateAdjustmentTemplateRequest.template:type_name -> api.v1.AdjustmentTemplate
	16, // 15: api.v1.ListAdjustmentTemplatesResponse.templates:type_name -> api.v1.AdjustmentTemplate
	24, // 16: api.v1.Score.data:type_name -> api.v1.ScoreData
	26, // 17: api.v1.Adjustment.data:type_name -> api.v1.AdjustmentData
	23, // 18: api.v1.StageScore.score:type_name -> api.v1.Score
	25, // 19: api.v1.StageScore.adjustments:type_name -> api.v1.Adjustment
	24, // 20: api.v1.StageScoreData.score:type_name -> api.v1.ScoreData
	26, // 21: api.v1.StageScoreData.adjustments:type_name -> api.v1.AdjustmentData
	28, // 22: api.v1.CreateStageScoreRequest.data:type_name -> api.v1.StageScoreData
	27, // 23: api.v1.CreateStageScoreResponse.score:type_name -> api.v1.StageScore
	27, // 24: api.v1.UpdateStageScoreRequest.score:type_name -> api.v1.StageScore
	27, // 25: api.v1.UpdateStageScoreResponse.score:type_name -> api.v1.StageScore
	0,  // 26: api.v1.ListStageScoresRequest.verified_filter:type_name -> api.v1.StageScoreVerifiedFilter
	27, // 27: api.v1.ListStageScoresResponse.scores:type_name -> api.v1.StageScore
	1,  // 28: api.v1.AdminService.CreatePlayer:input_type -> api.v1.AdminServiceCreatePlayerRequest
	3,  // 29: api.v1.AdminService.UpdatePlayer:input_type -> api.v1.UpdatePlayerRequest
	5,  // 30: api.v1.AdminService.ListPlayers:input_type -> api.v1.ListPlayersRequest
	9,  // 31: api.v1.AdminService.ListVenues:input_type -> api.v1.ListVenuesRequest
	11, // 32: api.v1.AdminService.UpdateStage:input_type -> api.v1.UpdateStageRequest
	13, // 33: api.v1.AdminService.ListEventStages:input_type -> api.v1.ListEventStagesRequest
	17, // 34: api.v1.AdminService.CreateAdjustmentTemplate:input_type -> api.v1.CreateAdjustmentTemplateRequest
	19, // 35: api.v1.AdminService.UpdateAdjustmentTemplate:input_type -> api.v1.UpdateAdjustmentTemplateRequest
	21, // 36: api.v1.AdminService.ListAdjustmentTemplates:input_type -> api.v1.ListAdjustmentTemplatesRequest
	29, // 37: api.v1.AdminService.CreateStageScore:input_type -> api.v1.CreateStageScoreRequest
	31, // 38: api.v1.AdminService.UpdateStageScore:input_type -> api.v1.UpdateStageScoreRequest
	33, // 39: api.v1.AdminService.ListStageScores:input_type -> api.v1.ListStageScoresRequest
	35, // 40: api.v1.AdminService.DeleteStageScore:input_type -> api.v1.DeleteStageScoreRequest
	2,  // 41: api.v1.AdminService.CreatePlayer:output_type -> api.v1.AdminServiceCreatePlayerResponse
	4,  // 42: api.v1.AdminService.UpdatePlayer:output_type -> api.v1.UpdatePlayerResponse
	6,  // 43: api.v1.AdminService.ListPlayers:output_type -> api.v1.ListPlayersResponse
	10, // 44: api.v1.AdminService.ListVenues:output_type -> api.v1.ListVenuesResponse
	12, // 45: api.v1.AdminService.UpdateStage:output_type -> api.v1.UpdateStageResponse
	14, // 46: api.v1.AdminService.ListEventStages:output_type -> api.v1.ListEventStagesResponse
	18, // 47: api.v1.AdminService.CreateAdjustmentTemplate:output_type -> api.v1.CreateAdjustmentTemplateResponse
	20, // 48: api.v1.AdminService.UpdateAdjustmentTemplate:output_type -> api.v1.UpdateAdjustmentTemplateResponse
	22, // 49: api.v1.AdminService.ListAdjustmentTemplates:output_type -> api.v1.ListAdjustmentTemplatesResponse
	30, // 50: api.v1.AdminService.CreateStageScore:output_type -> api.v1.CreateStageScoreResponse
	32, // 51: api.v1.AdminService.UpdateStageScore:output_type -> api.v1.UpdateStageScoreResponse
	34, // 52: api.v1.AdminService.ListStageScores:output_type -> api.v1.ListStageScoresResponse
	36, // 53: api.v1.AdminService.DeleteStageScore:output_type -> api.v1.DeleteStageScoreResponse
	41, // [41:54] is the sub-list for method output_type
	28, // [28:41] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_api_v1_admin_proto_init() }
func file_api_v1_admin_proto_init() {
	if File_api_v1_admin_proto != nil {
		return
	}
	file_api_v1_shared_proto_init()
	file_api_v1_admin_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_v1_admin_proto_msgTypes[28].OneofWrappers = []any{}
	file_api_v1_admin_proto_msgTypes[32].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_admin_proto_rawDesc), len(file_api_v1_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_admin_proto_goTypes,
		DependencyIndexes: file_api_v1_admin_proto_depIdxs,
		EnumInfos:         file_api_v1_admin_proto_enumTypes,
		MessageInfos:      file_api_v1_admin_proto_msgTypes,
	}.Build()
	File_api_v1_admin_proto = out.File
	file_api_v1_admin_proto_goTypes = nil
	file_api_v1_admin_proto_depIdxs = nil
}
