version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dogsled
    - dupl
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - godox
    - lll
    - maintidx
    - mnd
    - prealloc
    - rowserrcheck
    - tagalign
    - tagliatelle
    - testpackage
    - unparam
    - unused
    - varnamelen
  settings:
    exhaustive:
      check:
        - switch
        - map
    wsl:
      allow-cuddle-declarations: true
      force-err-cuddling: true
    recvcheck:
      exclusions:
        - "*.Value"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - prefix(github.com/pubgolf/pubgolf)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
