// Code generated by "enumer -sql -transform snake-upper -type VenueDescriptionItemType ./api/internal/lib/models"; DO NOT EDIT.

package models

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _VenueDescriptionItemTypeName = "VENUE_DESCRIPTION_ITEM_TYPE_UNSPECIFIEDVENUE_DESCRIPTION_ITEM_TYPE_DEFAULTVENUE_DESCRIPTION_ITEM_TYPE_WARNINGVENUE_DESCRIPTION_ITEM_TYPE_RULE"

var _VenueDescriptionItemTypeIndex = [...]uint8{0, 39, 74, 109, 141}

const _VenueDescriptionItemTypeLowerName = "venue_description_item_type_unspecifiedvenue_description_item_type_defaultvenue_description_item_type_warningvenue_description_item_type_rule"

func (i VenueDescriptionItemType) String() string {
	if i < 0 || i >= VenueDescriptionItemType(len(_VenueDescriptionItemTypeIndex)-1) {
		return fmt.Sprintf("VenueDescriptionItemType(%d)", i)
	}
	return _VenueDescriptionItemTypeName[_VenueDescriptionItemTypeIndex[i]:_VenueDescriptionItemTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _VenueDescriptionItemTypeNoOp() {
	var x [1]struct{}
	_ = x[VenueDescriptionItemTypeUnspecified-(0)]
	_ = x[VenueDescriptionItemTypeDefault-(1)]
	_ = x[VenueDescriptionItemTypeWarning-(2)]
	_ = x[VenueDescriptionItemTypeRule-(3)]
}

var _VenueDescriptionItemTypeValues = []VenueDescriptionItemType{VenueDescriptionItemTypeUnspecified, VenueDescriptionItemTypeDefault, VenueDescriptionItemTypeWarning, VenueDescriptionItemTypeRule}

var _VenueDescriptionItemTypeNameToValueMap = map[string]VenueDescriptionItemType{
	_VenueDescriptionItemTypeName[0:39]:         VenueDescriptionItemTypeUnspecified,
	_VenueDescriptionItemTypeLowerName[0:39]:    VenueDescriptionItemTypeUnspecified,
	_VenueDescriptionItemTypeName[39:74]:        VenueDescriptionItemTypeDefault,
	_VenueDescriptionItemTypeLowerName[39:74]:   VenueDescriptionItemTypeDefault,
	_VenueDescriptionItemTypeName[74:109]:       VenueDescriptionItemTypeWarning,
	_VenueDescriptionItemTypeLowerName[74:109]:  VenueDescriptionItemTypeWarning,
	_VenueDescriptionItemTypeName[109:141]:      VenueDescriptionItemTypeRule,
	_VenueDescriptionItemTypeLowerName[109:141]: VenueDescriptionItemTypeRule,
}

var _VenueDescriptionItemTypeNames = []string{
	_VenueDescriptionItemTypeName[0:39],
	_VenueDescriptionItemTypeName[39:74],
	_VenueDescriptionItemTypeName[74:109],
	_VenueDescriptionItemTypeName[109:141],
}

// VenueDescriptionItemTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func VenueDescriptionItemTypeString(s string) (VenueDescriptionItemType, error) {
	if val, ok := _VenueDescriptionItemTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _VenueDescriptionItemTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to VenueDescriptionItemType values", s)
}

// VenueDescriptionItemTypeValues returns all values of the enum
func VenueDescriptionItemTypeValues() []VenueDescriptionItemType {
	return _VenueDescriptionItemTypeValues
}

// VenueDescriptionItemTypeStrings returns a slice of all String values of the enum
func VenueDescriptionItemTypeStrings() []string {
	strs := make([]string, len(_VenueDescriptionItemTypeNames))
	copy(strs, _VenueDescriptionItemTypeNames)
	return strs
}

// IsAVenueDescriptionItemType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i VenueDescriptionItemType) IsAVenueDescriptionItemType() bool {
	for _, v := range _VenueDescriptionItemTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i VenueDescriptionItemType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *VenueDescriptionItemType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of VenueDescriptionItemType: %[1]T(%[1]v)", value)
	}

	val, err := VenueDescriptionItemTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
