// PubGolf defines the app-facing API service for the in-game apps.

// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts"
// @generated from file api/v1/pubgolf.proto (package api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ClientVersionRequest, ClientVersionResponse, GetContentItemRequest, GetContentItemResponse, GetPlayerByNameRequest, GetPlayerByNameResponse, GetScheduleRequest, GetScheduleResponse, GetScoresForCategoryRequest, GetScoresForCategoryResponse, GetScoresForPlayerRequest, GetScoresForPlayerResponse, GetScoresForVenueRequest, GetScoresForVenueResponse, GetVenueRequest, GetVenueResponse, ListContentItemsRequest, ListContentItemsResponse, PubGolfServiceCreatePlayerRequest, PubGolfServiceCreatePlayerResponse } from "./pubgolf_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * PubGolfService is the API server which handles all score keeping, scheduling and account management for pub golf.
 *
 * @generated from service api.v1.PubGolfService
 */
export const PubGolfService = {
  typeName: "api.v1.PubGolfService",
  methods: {
    /**
     * ClientVersion indicates to the server that a client of a given version is attempting to connect, and allows the server to respond with a "soft" or "hard" upgrade notification.
     *
     * @generated from rpc api.v1.PubGolfService.ClientVersion
     */
    clientVersion: {
      name: "ClientVersion",
      I: ClientVersionRequest,
      O: ClientVersionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CreatePlayer creates a new player profile for a given event.
     *
     * @generated from rpc api.v1.PubGolfService.CreatePlayer
     */
    createPlayer: {
      name: "CreatePlayer",
      I: PubGolfServiceCreatePlayerRequest,
      O: PubGolfServiceCreatePlayerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetSchedule returns the list of visble venues, as well as the next venue transition time. It optionally accepts a data version to allow local caching.
     *
     * @generated from rpc api.v1.PubGolfService.GetSchedule
     */
    getSchedule: {
      name: "GetSchedule",
      I: GetScheduleRequest,
      O: GetScheduleResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetVenue performs a bulk lookup of venue metadata by ID. IDs are scoped to an event key.
     *
     * @generated from rpc api.v1.PubGolfService.GetVenue
     */
    getVenue: {
      name: "GetVenue",
      I: GetVenueRequest,
      O: GetVenueResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ListContentItems
     *
     * @generated from rpc api.v1.PubGolfService.ListContentItems
     */
    listContentItems: {
      name: "ListContentItems",
      I: ListContentItemsRequest,
      O: ListContentItemsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetContentItem
     *
     * @generated from rpc api.v1.PubGolfService.GetContentItem
     */
    getContentItem: {
      name: "GetContentItem",
      I: GetContentItemRequest,
      O: GetContentItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetPlayerByName
     *
     * @generated from rpc api.v1.PubGolfService.GetPlayerByName
     */
    getPlayerByName: {
      name: "GetPlayerByName",
      I: GetPlayerByNameRequest,
      O: GetPlayerByNameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetScoresForCategory
     *
     * @generated from rpc api.v1.PubGolfService.GetScoresForCategory
     */
    getScoresForCategory: {
      name: "GetScoresForCategory",
      I: GetScoresForCategoryRequest,
      O: GetScoresForCategoryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetScoresForPlayer
     *
     * @generated from rpc api.v1.PubGolfService.GetScoresForPlayer
     */
    getScoresForPlayer: {
      name: "GetScoresForPlayer",
      I: GetScoresForPlayerRequest,
      O: GetScoresForPlayerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetScoresForVenue
     *
     * @generated from rpc api.v1.PubGolfService.GetScoresForVenue
     */
    getScoresForVenue: {
      name: "GetScoresForVenue",
      I: GetScoresForVenueRequest,
      O: GetScoresForVenueResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

