// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package dbc

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.adjustmentTemplatesByStageIDStmt, err = db.PrepareContext(ctx, adjustmentTemplatesByStageID); err != nil {
		return nil, fmt.Errorf("error preparing query AdjustmentTemplatesByStageID: %w", err)
	}
	if q.adjustmentsByPlayerStageStmt, err = db.PrepareContext(ctx, adjustmentsByPlayerStage); err != nil {
		return nil, fmt.Errorf("error preparing query AdjustmentsByPlayerStage: %w", err)
	}
	if q.allVenuesStmt, err = db.PrepareContext(ctx, allVenues); err != nil {
		return nil, fmt.Errorf("error preparing query AllVenues: %w", err)
	}
	if q.createAdjustmentStmt, err = db.PrepareContext(ctx, createAdjustment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAdjustment: %w", err)
	}
	if q.createAdjustmentTemplateStmt, err = db.PrepareContext(ctx, createAdjustmentTemplate); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAdjustmentTemplate: %w", err)
	}
	if q.createAdjustmentWithTemplateStmt, err = db.PrepareContext(ctx, createAdjustmentWithTemplate); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAdjustmentWithTemplate: %w", err)
	}
	if q.createPlayerStmt, err = db.PrepareContext(ctx, createPlayer); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePlayer: %w", err)
	}
	if q.deactivateAuthTokensStmt, err = db.PrepareContext(ctx, deactivateAuthTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeactivateAuthTokens: %w", err)
	}
	if q.deleteAdjustmentStmt, err = db.PrepareContext(ctx, deleteAdjustment); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAdjustment: %w", err)
	}
	if q.deleteAdjustmentsForPlayerStageStmt, err = db.PrepareContext(ctx, deleteAdjustmentsForPlayerStage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAdjustmentsForPlayerStage: %w", err)
	}
	if q.deletePlayerStmt, err = db.PrepareContext(ctx, deletePlayer); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePlayer: %w", err)
	}
	if q.deleteScoreForPlayerStageStmt, err = db.PrepareContext(ctx, deleteScoreForPlayerStage); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteScoreForPlayerStage: %w", err)
	}
	if q.eventAdjustmentTemplatesStmt, err = db.PrepareContext(ctx, eventAdjustmentTemplates); err != nil {
		return nil, fmt.Errorf("error preparing query EventAdjustmentTemplates: %w", err)
	}
	if q.eventAdjustmentsStmt, err = db.PrepareContext(ctx, eventAdjustments); err != nil {
		return nil, fmt.Errorf("error preparing query EventAdjustments: %w", err)
	}
	if q.eventCacheVersionByHashStmt, err = db.PrepareContext(ctx, eventCacheVersionByHash); err != nil {
		return nil, fmt.Errorf("error preparing query EventCacheVersionByHash: %w", err)
	}
	if q.eventIDByKeyStmt, err = db.PrepareContext(ctx, eventIDByKey); err != nil {
		return nil, fmt.Errorf("error preparing query EventIDByKey: %w", err)
	}
	if q.eventPlayersStmt, err = db.PrepareContext(ctx, eventPlayers); err != nil {
		return nil, fmt.Errorf("error preparing query EventPlayers: %w", err)
	}
	if q.eventScheduleStmt, err = db.PrepareContext(ctx, eventSchedule); err != nil {
		return nil, fmt.Errorf("error preparing query EventSchedule: %w", err)
	}
	if q.eventScheduleWithDetailsStmt, err = db.PrepareContext(ctx, eventScheduleWithDetails); err != nil {
		return nil, fmt.Errorf("error preparing query EventScheduleWithDetails: %w", err)
	}
	if q.eventScoresStmt, err = db.PrepareContext(ctx, eventScores); err != nil {
		return nil, fmt.Errorf("error preparing query EventScores: %w", err)
	}
	if q.eventStartTimeStmt, err = db.PrepareContext(ctx, eventStartTime); err != nil {
		return nil, fmt.Errorf("error preparing query EventStartTime: %w", err)
	}
	if q.generateAuthTokenStmt, err = db.PrepareContext(ctx, generateAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query GenerateAuthToken: %w", err)
	}
	if q.phoneNumberIsVerifiedStmt, err = db.PrepareContext(ctx, phoneNumberIsVerified); err != nil {
		return nil, fmt.Errorf("error preparing query PhoneNumberIsVerified: %w", err)
	}
	if q.playerAdjustmentsStmt, err = db.PrepareContext(ctx, playerAdjustments); err != nil {
		return nil, fmt.Errorf("error preparing query PlayerAdjustments: %w", err)
	}
	if q.playerByIDStmt, err = db.PrepareContext(ctx, playerByID); err != nil {
		return nil, fmt.Errorf("error preparing query PlayerByID: %w", err)
	}
	if q.playerCategoryForEventStmt, err = db.PrepareContext(ctx, playerCategoryForEvent); err != nil {
		return nil, fmt.Errorf("error preparing query PlayerCategoryForEvent: %w", err)
	}
	if q.playerIDByAuthTokenStmt, err = db.PrepareContext(ctx, playerIDByAuthToken); err != nil {
		return nil, fmt.Errorf("error preparing query PlayerIDByAuthToken: %w", err)
	}
	if q.playerRegisteredForEventStmt, err = db.PrepareContext(ctx, playerRegisteredForEvent); err != nil {
		return nil, fmt.Errorf("error preparing query PlayerRegisteredForEvent: %w", err)
	}
	if q.playerRegistrationsByIDStmt, err = db.PrepareContext(ctx, playerRegistrationsByID); err != nil {
		return nil, fmt.Errorf("error preparing query PlayerRegistrationsByID: %w", err)
	}
	if q.playerScoresStmt, err = db.PrepareContext(ctx, playerScores); err != nil {
		return nil, fmt.Errorf("error preparing query PlayerScores: %w", err)
	}
	if q.scoreByPlayerStageStmt, err = db.PrepareContext(ctx, scoreByPlayerStage); err != nil {
		return nil, fmt.Errorf("error preparing query ScoreByPlayerStage: %w", err)
	}
	if q.scoringCriteriaStmt, err = db.PrepareContext(ctx, scoringCriteria); err != nil {
		return nil, fmt.Errorf("error preparing query ScoringCriteria: %w", err)
	}
	if q.setEventCacheKeysStmt, err = db.PrepareContext(ctx, setEventCacheKeys); err != nil {
		return nil, fmt.Errorf("error preparing query SetEventCacheKeys: %w", err)
	}
	if q.setEventVenueKeysStmt, err = db.PrepareContext(ctx, setEventVenueKeys); err != nil {
		return nil, fmt.Errorf("error preparing query SetEventVenueKeys: %w", err)
	}
	if q.setNextEventVenueKeyStmt, err = db.PrepareContext(ctx, setNextEventVenueKey); err != nil {
		return nil, fmt.Errorf("error preparing query SetNextEventVenueKey: %w", err)
	}
	if q.stageIDByVenueKeyStmt, err = db.PrepareContext(ctx, stageIDByVenueKey); err != nil {
		return nil, fmt.Errorf("error preparing query StageIDByVenueKey: %w", err)
	}
	if q.updateAdjustmentTemplateStmt, err = db.PrepareContext(ctx, updateAdjustmentTemplate); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAdjustmentTemplate: %w", err)
	}
	if q.updatePlayerStmt, err = db.PrepareContext(ctx, updatePlayer); err != nil {
		return nil, fmt.Errorf("error preparing query UpdatePlayer: %w", err)
	}
	if q.updateRuleByStageStmt, err = db.PrepareContext(ctx, updateRuleByStage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRuleByStage: %w", err)
	}
	if q.updateStageStmt, err = db.PrepareContext(ctx, updateStage); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateStage: %w", err)
	}
	if q.upsertRegistrationStmt, err = db.PrepareContext(ctx, upsertRegistration); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertRegistration: %w", err)
	}
	if q.upsertScoreStmt, err = db.PrepareContext(ctx, upsertScore); err != nil {
		return nil, fmt.Errorf("error preparing query UpsertScore: %w", err)
	}
	if q.venueByKeyStmt, err = db.PrepareContext(ctx, venueByKey); err != nil {
		return nil, fmt.Errorf("error preparing query VenueByKey: %w", err)
	}
	if q.verifyPhoneNumberStmt, err = db.PrepareContext(ctx, verifyPhoneNumber); err != nil {
		return nil, fmt.Errorf("error preparing query VerifyPhoneNumber: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.adjustmentTemplatesByStageIDStmt != nil {
		if cerr := q.adjustmentTemplatesByStageIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adjustmentTemplatesByStageIDStmt: %w", cerr)
		}
	}
	if q.adjustmentsByPlayerStageStmt != nil {
		if cerr := q.adjustmentsByPlayerStageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing adjustmentsByPlayerStageStmt: %w", cerr)
		}
	}
	if q.allVenuesStmt != nil {
		if cerr := q.allVenuesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing allVenuesStmt: %w", cerr)
		}
	}
	if q.createAdjustmentStmt != nil {
		if cerr := q.createAdjustmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAdjustmentStmt: %w", cerr)
		}
	}
	if q.createAdjustmentTemplateStmt != nil {
		if cerr := q.createAdjustmentTemplateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAdjustmentTemplateStmt: %w", cerr)
		}
	}
	if q.createAdjustmentWithTemplateStmt != nil {
		if cerr := q.createAdjustmentWithTemplateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAdjustmentWithTemplateStmt: %w", cerr)
		}
	}
	if q.createPlayerStmt != nil {
		if cerr := q.createPlayerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPlayerStmt: %w", cerr)
		}
	}
	if q.deactivateAuthTokensStmt != nil {
		if cerr := q.deactivateAuthTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deactivateAuthTokensStmt: %w", cerr)
		}
	}
	if q.deleteAdjustmentStmt != nil {
		if cerr := q.deleteAdjustmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAdjustmentStmt: %w", cerr)
		}
	}
	if q.deleteAdjustmentsForPlayerStageStmt != nil {
		if cerr := q.deleteAdjustmentsForPlayerStageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAdjustmentsForPlayerStageStmt: %w", cerr)
		}
	}
	if q.deletePlayerStmt != nil {
		if cerr := q.deletePlayerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePlayerStmt: %w", cerr)
		}
	}
	if q.deleteScoreForPlayerStageStmt != nil {
		if cerr := q.deleteScoreForPlayerStageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteScoreForPlayerStageStmt: %w", cerr)
		}
	}
	if q.eventAdjustmentTemplatesStmt != nil {
		if cerr := q.eventAdjustmentTemplatesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing eventAdjustmentTemplatesStmt: %w", cerr)
		}
	}
	if q.eventAdjustmentsStmt != nil {
		if cerr := q.eventAdjustmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing eventAdjustmentsStmt: %w", cerr)
		}
	}
	if q.eventCacheVersionByHashStmt != nil {
		if cerr := q.eventCacheVersionByHashStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing eventCacheVersionByHashStmt: %w", cerr)
		}
	}
	if q.eventIDByKeyStmt != nil {
		if cerr := q.eventIDByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing eventIDByKeyStmt: %w", cerr)
		}
	}
	if q.eventPlayersStmt != nil {
		if cerr := q.eventPlayersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing eventPlayersStmt: %w", cerr)
		}
	}
	if q.eventScheduleStmt != nil {
		if cerr := q.eventScheduleStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing eventScheduleStmt: %w", cerr)
		}
	}
	if q.eventScheduleWithDetailsStmt != nil {
		if cerr := q.eventScheduleWithDetailsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing eventScheduleWithDetailsStmt: %w", cerr)
		}
	}
	if q.eventScoresStmt != nil {
		if cerr := q.eventScoresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing eventScoresStmt: %w", cerr)
		}
	}
	if q.eventStartTimeStmt != nil {
		if cerr := q.eventStartTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing eventStartTimeStmt: %w", cerr)
		}
	}
	if q.generateAuthTokenStmt != nil {
		if cerr := q.generateAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing generateAuthTokenStmt: %w", cerr)
		}
	}
	if q.phoneNumberIsVerifiedStmt != nil {
		if cerr := q.phoneNumberIsVerifiedStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing phoneNumberIsVerifiedStmt: %w", cerr)
		}
	}
	if q.playerAdjustmentsStmt != nil {
		if cerr := q.playerAdjustmentsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing playerAdjustmentsStmt: %w", cerr)
		}
	}
	if q.playerByIDStmt != nil {
		if cerr := q.playerByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing playerByIDStmt: %w", cerr)
		}
	}
	if q.playerCategoryForEventStmt != nil {
		if cerr := q.playerCategoryForEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing playerCategoryForEventStmt: %w", cerr)
		}
	}
	if q.playerIDByAuthTokenStmt != nil {
		if cerr := q.playerIDByAuthTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing playerIDByAuthTokenStmt: %w", cerr)
		}
	}
	if q.playerRegisteredForEventStmt != nil {
		if cerr := q.playerRegisteredForEventStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing playerRegisteredForEventStmt: %w", cerr)
		}
	}
	if q.playerRegistrationsByIDStmt != nil {
		if cerr := q.playerRegistrationsByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing playerRegistrationsByIDStmt: %w", cerr)
		}
	}
	if q.playerScoresStmt != nil {
		if cerr := q.playerScoresStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing playerScoresStmt: %w", cerr)
		}
	}
	if q.scoreByPlayerStageStmt != nil {
		if cerr := q.scoreByPlayerStageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing scoreByPlayerStageStmt: %w", cerr)
		}
	}
	if q.scoringCriteriaStmt != nil {
		if cerr := q.scoringCriteriaStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing scoringCriteriaStmt: %w", cerr)
		}
	}
	if q.setEventCacheKeysStmt != nil {
		if cerr := q.setEventCacheKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setEventCacheKeysStmt: %w", cerr)
		}
	}
	if q.setEventVenueKeysStmt != nil {
		if cerr := q.setEventVenueKeysStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setEventVenueKeysStmt: %w", cerr)
		}
	}
	if q.setNextEventVenueKeyStmt != nil {
		if cerr := q.setNextEventVenueKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setNextEventVenueKeyStmt: %w", cerr)
		}
	}
	if q.stageIDByVenueKeyStmt != nil {
		if cerr := q.stageIDByVenueKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing stageIDByVenueKeyStmt: %w", cerr)
		}
	}
	if q.updateAdjustmentTemplateStmt != nil {
		if cerr := q.updateAdjustmentTemplateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAdjustmentTemplateStmt: %w", cerr)
		}
	}
	if q.updatePlayerStmt != nil {
		if cerr := q.updatePlayerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updatePlayerStmt: %w", cerr)
		}
	}
	if q.updateRuleByStageStmt != nil {
		if cerr := q.updateRuleByStageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRuleByStageStmt: %w", cerr)
		}
	}
	if q.updateStageStmt != nil {
		if cerr := q.updateStageStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateStageStmt: %w", cerr)
		}
	}
	if q.upsertRegistrationStmt != nil {
		if cerr := q.upsertRegistrationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertRegistrationStmt: %w", cerr)
		}
	}
	if q.upsertScoreStmt != nil {
		if cerr := q.upsertScoreStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing upsertScoreStmt: %w", cerr)
		}
	}
	if q.venueByKeyStmt != nil {
		if cerr := q.venueByKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing venueByKeyStmt: %w", cerr)
		}
	}
	if q.verifyPhoneNumberStmt != nil {
		if cerr := q.verifyPhoneNumberStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing verifyPhoneNumberStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                  DBTX
	tx                                  *sql.Tx
	adjustmentTemplatesByStageIDStmt    *sql.Stmt
	adjustmentsByPlayerStageStmt        *sql.Stmt
	allVenuesStmt                       *sql.Stmt
	createAdjustmentStmt                *sql.Stmt
	createAdjustmentTemplateStmt        *sql.Stmt
	createAdjustmentWithTemplateStmt    *sql.Stmt
	createPlayerStmt                    *sql.Stmt
	deactivateAuthTokensStmt            *sql.Stmt
	deleteAdjustmentStmt                *sql.Stmt
	deleteAdjustmentsForPlayerStageStmt *sql.Stmt
	deletePlayerStmt                    *sql.Stmt
	deleteScoreForPlayerStageStmt       *sql.Stmt
	eventAdjustmentTemplatesStmt        *sql.Stmt
	eventAdjustmentsStmt                *sql.Stmt
	eventCacheVersionByHashStmt         *sql.Stmt
	eventIDByKeyStmt                    *sql.Stmt
	eventPlayersStmt                    *sql.Stmt
	eventScheduleStmt                   *sql.Stmt
	eventScheduleWithDetailsStmt        *sql.Stmt
	eventScoresStmt                     *sql.Stmt
	eventStartTimeStmt                  *sql.Stmt
	generateAuthTokenStmt               *sql.Stmt
	phoneNumberIsVerifiedStmt           *sql.Stmt
	playerAdjustmentsStmt               *sql.Stmt
	playerByIDStmt                      *sql.Stmt
	playerCategoryForEventStmt          *sql.Stmt
	playerIDByAuthTokenStmt             *sql.Stmt
	playerRegisteredForEventStmt        *sql.Stmt
	playerRegistrationsByIDStmt         *sql.Stmt
	playerScoresStmt                    *sql.Stmt
	scoreByPlayerStageStmt              *sql.Stmt
	scoringCriteriaStmt                 *sql.Stmt
	setEventCacheKeysStmt               *sql.Stmt
	setEventVenueKeysStmt               *sql.Stmt
	setNextEventVenueKeyStmt            *sql.Stmt
	stageIDByVenueKeyStmt               *sql.Stmt
	updateAdjustmentTemplateStmt        *sql.Stmt
	updatePlayerStmt                    *sql.Stmt
	updateRuleByStageStmt               *sql.Stmt
	updateStageStmt                     *sql.Stmt
	upsertRegistrationStmt              *sql.Stmt
	upsertScoreStmt                     *sql.Stmt
	venueByKeyStmt                      *sql.Stmt
	verifyPhoneNumberStmt               *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                  tx,
		tx:                                  tx,
		adjustmentTemplatesByStageIDStmt:    q.adjustmentTemplatesByStageIDStmt,
		adjustmentsByPlayerStageStmt:        q.adjustmentsByPlayerStageStmt,
		allVenuesStmt:                       q.allVenuesStmt,
		createAdjustmentStmt:                q.createAdjustmentStmt,
		createAdjustmentTemplateStmt:        q.createAdjustmentTemplateStmt,
		createAdjustmentWithTemplateStmt:    q.createAdjustmentWithTemplateStmt,
		createPlayerStmt:                    q.createPlayerStmt,
		deactivateAuthTokensStmt:            q.deactivateAuthTokensStmt,
		deleteAdjustmentStmt:                q.deleteAdjustmentStmt,
		deleteAdjustmentsForPlayerStageStmt: q.deleteAdjustmentsForPlayerStageStmt,
		deletePlayerStmt:                    q.deletePlayerStmt,
		deleteScoreForPlayerStageStmt:       q.deleteScoreForPlayerStageStmt,
		eventAdjustmentTemplatesStmt:        q.eventAdjustmentTemplatesStmt,
		eventAdjustmentsStmt:                q.eventAdjustmentsStmt,
		eventCacheVersionByHashStmt:         q.eventCacheVersionByHashStmt,
		eventIDByKeyStmt:                    q.eventIDByKeyStmt,
		eventPlayersStmt:                    q.eventPlayersStmt,
		eventScheduleStmt:                   q.eventScheduleStmt,
		eventScheduleWithDetailsStmt:        q.eventScheduleWithDetailsStmt,
		eventScoresStmt:                     q.eventScoresStmt,
		eventStartTimeStmt:                  q.eventStartTimeStmt,
		generateAuthTokenStmt:               q.generateAuthTokenStmt,
		phoneNumberIsVerifiedStmt:           q.phoneNumberIsVerifiedStmt,
		playerAdjustmentsStmt:               q.playerAdjustmentsStmt,
		playerByIDStmt:                      q.playerByIDStmt,
		playerCategoryForEventStmt:          q.playerCategoryForEventStmt,
		playerIDByAuthTokenStmt:             q.playerIDByAuthTokenStmt,
		playerRegisteredForEventStmt:        q.playerRegisteredForEventStmt,
		playerRegistrationsByIDStmt:         q.playerRegistrationsByIDStmt,
		playerScoresStmt:                    q.playerScoresStmt,
		scoreByPlayerStageStmt:              q.scoreByPlayerStageStmt,
		scoringCriteriaStmt:                 q.scoringCriteriaStmt,
		setEventCacheKeysStmt:               q.setEventCacheKeysStmt,
		setEventVenueKeysStmt:               q.setEventVenueKeysStmt,
		setNextEventVenueKeyStmt:            q.setNextEventVenueKeyStmt,
		stageIDByVenueKeyStmt:               q.stageIDByVenueKeyStmt,
		updateAdjustmentTemplateStmt:        q.updateAdjustmentTemplateStmt,
		updatePlayerStmt:                    q.updatePlayerStmt,
		updateRuleByStageStmt:               q.updateRuleByStageStmt,
		updateStageStmt:                     q.updateStageStmt,
		upsertRegistrationStmt:              q.upsertRegistrationStmt,
		upsertScoreStmt:                     q.upsertScoreStmt,
		venueByKeyStmt:                      q.venueByKeyStmt,
		verifyPhoneNumberStmt:               q.verifyPhoneNumberStmt,
	}
}
