// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package dbc

import (
	"database/sql"
	"time"

	"github.com/pubgolf/pubgolf/api/internal/lib/models"
)

type Adjustment struct {
	ID        models.AdjustmentID
	StageID   models.StageID
	PlayerID  models.PlayerID
	Value     int32
	Label     string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type AuthToken struct {
	ID        models.DatabaseULID
	PlayerID  models.DatabaseULID
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type EnumScoringCategory struct {
	Value string
}

type Event struct {
	ID                          models.EventID
	Key                         string
	StartsAt                    time.Time
	CurrentVenueKey             uint32
	CurrentScheduleCacheVersion uint32
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	DeletedAt                   sql.NullTime
	CurrentScheduleCacheHash    []byte
}

type EventPlayer struct {
	EventID         models.EventID
	PlayerID        models.PlayerID
	ScoringCategory models.ScoringCategory
	CreatedAt       time.Time
	DeletedAt       sql.NullTime
}

type Player struct {
	ID                  models.PlayerID
	Name                string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	DeletedAt           sql.NullTime
	PhoneNumber         models.PhoneNum
	PhoneNumberVerified bool
}

type Rule struct {
	ID          models.DatabaseULID
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Score struct {
	ID        models.ScoreID
	StageID   models.StageID
	PlayerID  models.PlayerID
	Value     uint32
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Stage struct {
	EventID         models.EventID
	VenueID         models.VenueID
	VenueKey        models.VenueKey
	Rank            int32
	DurationMinutes uint32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
	RuleID          models.DatabaseULID
	ID              models.StageID
}

type Venue struct {
	ID        models.VenueID
	Name      string
	Address   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	ImageUrl  sql.NullString
}
