// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package dbc

import (
	"database/sql"
	"time"

	"github.com/pubgolf/pubgolf/api/internal/lib/models"
)

type EnumScoringCategory struct {
	Value string
}

type Event struct {
	ID                          models.EventID
	Key                         string
	StartsAt                    time.Time
	CurrentVenueKey             uint32
	CurrentScheduleCacheVersion uint32
	CreatedAt                   time.Time
	UpdatedAt                   time.Time
	DeletedAt                   sql.NullTime
}

type EventVenue struct {
	EventID         models.EventID
	VenueID         models.VenueID
	VenueKey        models.VenueKey
	Rank            int32
	DurationMinutes uint32
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type Player struct {
	ID              models.PlayerID
	EventID         models.EventID
	Name            string
	ScoringCategory models.ScoringCategory
	CreatedAt       time.Time
	UpdatedAt       time.Time
	DeletedAt       sql.NullTime
}

type Venue struct {
	ID        models.VenueID
	Name      string
	Address   string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
