// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: players.sql

package dbc

import (
	"context"

	"github.com/pubgolf/pubgolf/api/internal/lib/models"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players(event_id, name, scoring_category, updated_at)
  VALUES ($1, $2, $3, now())
RETURNING
  id, name, scoring_category
`

type CreatePlayerParams struct {
	EventID         models.EventID
	Name            string
	ScoringCategory models.ScoringCategory
}

type CreatePlayerRow struct {
	ID              models.PlayerID
	Name            string
	ScoringCategory models.ScoringCategory
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (CreatePlayerRow, error) {
	row := q.queryRow(ctx, q.createPlayerStmt, createPlayer, arg.EventID, arg.Name, arg.ScoringCategory)
	var i CreatePlayerRow
	err := row.Scan(&i.ID, &i.Name, &i.ScoringCategory)
	return i, err
}

const eventPlayers = `-- name: EventPlayers :many
SELECT
  id,
  name,
  scoring_category
FROM
  players
WHERE
  event_id = $1
  AND deleted_at IS NULL
ORDER BY
  name ASC
`

type EventPlayersRow struct {
	ID              models.PlayerID
	Name            string
	ScoringCategory models.ScoringCategory
}

func (q *Queries) EventPlayers(ctx context.Context, eventID models.EventID) ([]EventPlayersRow, error) {
	rows, err := q.query(ctx, q.eventPlayersStmt, eventPlayers, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventPlayersRow
	for rows.Next() {
		var i EventPlayersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ScoringCategory); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayer = `-- name: UpdatePlayer :one
UPDATE
  players
SET
  name = $2,
  scoring_category = $3,
  updated_at = now()
WHERE
  id = $1
RETURNING
  id,
  name,
  scoring_category
`

type UpdatePlayerParams struct {
	ID              models.PlayerID
	Name            string
	ScoringCategory models.ScoringCategory
}

type UpdatePlayerRow struct {
	ID              models.PlayerID
	Name            string
	ScoringCategory models.ScoringCategory
}

func (q *Queries) UpdatePlayer(ctx context.Context, arg UpdatePlayerParams) (UpdatePlayerRow, error) {
	row := q.queryRow(ctx, q.updatePlayerStmt, updatePlayer, arg.ID, arg.Name, arg.ScoringCategory)
	var i UpdatePlayerRow
	err := row.Scan(&i.ID, &i.Name, &i.ScoringCategory)
	return i, err
}
