// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rule_items.sql

package dbc

import (
	"context"

	"github.com/lib/pq"
	"github.com/pubgolf/pubgolf/api/internal/lib/models"
)

const createRuleItem = `-- name: CreateRuleItem :exec
INSERT INTO rule_items (stages_id, content, item_type, audiences, rank)
  VALUES ($1, $2, $3, $4, $5)
`

type CreateRuleItemParams struct {
	StagesID  models.StageID
	Content   string
	ItemType  string
	Audiences []string
	Rank      int32
}

func (q *Queries) CreateRuleItem(ctx context.Context, arg CreateRuleItemParams) error {
	_, err := q.exec(ctx, q.createRuleItemStmt, createRuleItem,
		arg.StagesID,
		arg.Content,
		arg.ItemType,
		pq.Array(arg.Audiences),
		arg.Rank,
	)
	return err
}

const deleteRuleItemsByStageID = `-- name: DeleteRuleItemsByStageID :exec
UPDATE
  rule_items
SET
  deleted_at = now()
WHERE
  stages_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) DeleteRuleItemsByStageID(ctx context.Context, stagesID models.StageID) error {
	_, err := q.exec(ctx, q.deleteRuleItemsByStageIDStmt, deleteRuleItemsByStageID, stagesID)
	return err
}

const ruleItemsByStageIDs = `-- name: RuleItemsByStageIDs :many
SELECT
  id,
  stages_id,
  content,
  item_type,
  audiences,
  rank
FROM
  rule_items
WHERE
  stages_id = ANY($1::uuid[])
  AND deleted_at IS NULL
ORDER BY
  stages_id,
  rank ASC
`

type RuleItemsByStageIDsRow struct {
	ID        models.RuleItemID
	StagesID  models.StageID
	Content   string
	ItemType  string
	Audiences []string
	Rank      int32
}

func (q *Queries) RuleItemsByStageIDs(ctx context.Context, stageIds []models.DatabaseULID) ([]RuleItemsByStageIDsRow, error) {
	rows, err := q.query(ctx, q.ruleItemsByStageIDsStmt, ruleItemsByStageIDs, pq.Array(stageIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RuleItemsByStageIDsRow
	for rows.Next() {
		var i RuleItemsByStageIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.StagesID,
			&i.Content,
			&i.ItemType,
			pq.Array(&i.Audiences),
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
